In [1]:
import numpy as np

In [2]:
# Creación de un arreglo a partir de una lista
lista1 = [1, 2, 3, 4, 5]
arreglo1 = np.array(lista1)
arreglo1

array([1, 2, 3, 4, 5])

In [3]:
type(arreglo1)

numpy.ndarray

In [4]:
# Creación de un arreglo a partir de una lista de listas
lista2 = [[1,2,3],
          [4,5,6],
          [7,8,9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Las listas pueden contener diversos tipos de datos
lista = ["a", True, 1]
lista

['a', True, 1]

In [6]:
# Los arreglos sólo pueden tener un mismo tipo de datos
# Usan menos espacio en memoria
arreglo = np.array(lista)
arreglo # Solo se almacenaron textos

array(['a', 'True', '1'], dtype='<U21')

In [7]:
# Creación de arreglos con ceros
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# Creación de arreglo con números aleatorios uniformes entre 0 y 1
np.random.random((3,2))

array([[0.95110817, 0.07505166],
       [0.17819651, 0.28600239],
       [0.33348999, 0.56018123]])

In [9]:
# Creación de arreglos en un rango
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
arreglo1 = np.array([[1,2],
                     [5,7]])
arreglo2 = np.array([[8,9],
                     [5,7]])
arreglo3 = np.array([[1,2],
                     [5,7]])

In [12]:
arreglo_3D = np.array([arreglo1, arreglo2, arreglo3])
arreglo_3D

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [13]:
arreglo3 = np.zeros((5,4))
arreglo3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arreglo3.shape

(5, 4)

In [15]:
# Conversión de un arreglo multi-dimensional a uni-dimensional
lista2 = [[1,2,3],
          [4,5,6],
          [7,8,9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Cambio de dimensión de un arreglo
arreglo = np.array([[1,2],
                    [3,4],
                    [5,6]])
arreglo.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# Ejemplo de ERROR al momento de cambiar la dimensión
arreglo.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [19]:
# El atributo dtype
np.array([1.25, 2.43, 200.88]).dtype

dtype('float64')

In [20]:
arreglo_int = np.array([[1,2,3], [4,5,6]])
arreglo_int.dtype

dtype('int64')

In [21]:
arreglo_string = np.array(["Introducción", "a", "la", "programación"])
arreglo_string.dtype

dtype('<U12')

In [23]:
# Uso de dtype como argumento
arreglo = np.array([1.25, 2.43, 200.88], dtype = np.float32) # Mismo arreglo de arriba
arreglo.dtype

dtype('float32')

In [24]:
# Cambio de tipo de arreglo
arreglo_booleano = np.array([[True, False]], dtype = np.bool_)
arreglo_booleano.dtype

dtype('bool')

In [25]:
arreglo = arreglo_booleano.astype(np.int32)
arreglo

array([[1, 0]], dtype=int32)

In [26]:
# Homologación del tipo por jerarquía
np.array([0, 50, 50.8]).dtype

dtype('float64')

In [27]:
np.array([False, 42])

array([ 0, 42])