In [1]:
import numpy as np
accidentes = np.array([[0,1,1],
                       [1,0,1],
                       [1,3,2],
                       [2,2,0]])

In [2]:
# Inciso A
accidentes.sum()

14

In [3]:
# Inciso B
accid_areas = accidentes.sum(axis=0)
accid_areas

array([4, 6, 4])

In [4]:
print("Los accidentes del área 1:", accid_areas[0])
print("Los accidentes del área 2:", accid_areas[1])
print("Los accidentes del área 3:", accid_areas[2])

Los accidentes del área 1: 4
Los accidentes del área 2: 6
Los accidentes del área 3: 4


In [5]:
# Inciso C
accid_anios = accidentes.sum(axis=1)
accid_anios

array([2, 2, 6, 4])

In [6]:
# Conservación de dimensiones
accid_anios = accidentes.sum(axis=1, keepdims=True)
accid_anios

array([[2],
       [2],
       [6],
       [4]])

In [7]:
print("Los accidentes del año 1:", accid_anios[0])
print("Los accidentes del año 2:", accid_anios[1])
print("Los accidentes del año 3:", accid_anios[2])
print("Los accidentes del año 4:", accid_anios[3])

Los accidentes del año 1: [2]
Los accidentes del año 2: [2]
Los accidentes del año 3: [6]
Los accidentes del año 4: [4]


In [8]:
# Inciso D
maximo = accidentes.max()
minimo = accidentes.min()
print(f"Máximo de accidentes: {maximo}")
print(f"Mínimo de accidentes: {minimo}")

Máximo de accidentes: 3
Mínimo de accidentes: 0


In [9]:
# Inciso E
promedio = accidentes.mean()
print(f"Promedio de accidentes: {promedio}")

Promedio de accidentes: 1.1666666666666667


In [10]:
arreglo = np.array([[1,2,3],
                    [4,5,6]])
dimensiones = arreglo.shape
print(dimensiones[0]) # Renglones
print(dimensiones[1]) # Columnas
print(arreglo[0][0]) # Primer elemento

2
3
1


In [11]:
# Inciso A
import time
inicio = time.time()

arreglo_final = np.zeros((2,3))
for renglon in range(dimensiones[0]):
    for columna in range(dimensiones[1]):
        arreglo_final[renglon][columna] = arreglo[renglon][columna] + 3

fin = time.time()
print("Tiempo total de ejecución (segs.):", fin - inicio)
print(arreglo_final)

Tiempo total de ejecución (segs.): 0.00156402587890625
[[4. 5. 6.]
 [7. 8. 9.]]


In [12]:
# Inciso B
inicio = time.time()

arreglo_final = arreglo + 3
fin = time.time()
print("Tiempo total de ejecución (segs.):", fin - inicio)
print(arreglo_final)

Tiempo total de ejecución (segs.): 0.00030493736267089844
[[4 5 6]
 [7 8 9]]


In [13]:
# Multiplicación por un escalar
arreglo_prod = arreglo * 3
arreglo_prod

array([[ 3,  6,  9],
       [12, 15, 18]])

In [14]:
# Adición de 2 arreglos
arreglo1 = np.array([[1,2,3],
                     [4,5,6]])
arreglo2 = np.array([[7,8,9],
                     [10,11,12]])
arreglo3 = arreglo1 + arreglo2
arreglo3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [15]:
# Evaluación de condiciones
arreglo1 = np.array([[1,2,3],
                     [4,5,6]])
arreglo1 > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [16]:
# Las funciones de Python no están vectorizadas de origen
arreglo = np.array(["NumPy", "maneja", "vectorización"])
len(arreglo) > 5

False

In [17]:
# Transformación para vectorización la función "len"
len_vectorizada = np.vectorize(len)
len_vectorizada(arreglo) > 5

array([False,  True,  True])

In [18]:
# Broadcasting de renglones
arreglo = np.arange(10).reshape((2,5))
arreglo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
arreglo + np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [20]:
# Broadcasting de columnas
arreglo = np.arange(10).reshape((2,5))
arreglo + np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [21]:
arreglo + np.array([0,1])

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [22]:
# Volteo a un arreglo
arreglo = np.array([[1.1, 1.2, 1.3],
                    [2.1, 2.2, 2.3],
                    [4.1, 4.2, 4.3]])
np.flip(arreglo)

array([[4.3, 4.2, 4.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

In [23]:
# Transposición de un arreglo
arreglo = np.array([[1.1, 1.2, 1.3],
                    [2.1, 2.2, 2.3],
                    [4.1, 4.2, 4.3]])
np.transpose(arreglo)

array([[1.1, 2.1, 4.1],
       [1.2, 2.2, 4.2],
       [1.3, 2.3, 4.3]])

In [24]:
# Operación 1
np.array([[1,2], [3,4]]) * np.array([[5], [10]])

array([[ 5, 10],
       [30, 40]])

In [25]:
# Operación 2
np.array([[1,2], [3,4]]) - np.array([[5,10]])

array([[-4, -8],
       [-2, -6]])