In [1]:
import numpy as np

In [2]:
# Indexación de un solo elemento
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Extracción de elementos en forma ascendente
x[2]

2

In [4]:
# Extracción de elementos en forma descendente
x[-2]

8

In [5]:
x.shape = (2, 5) # Conversión del arreglo a formato bidimensional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x[1,3] # Extracción del elemento con índice 1 en renglón e índice 3 en columna

8

In [7]:
x[1][3] # Alternativa de extracción del elemento con índice 1 en renglón e índice 3 en columna

8

In [8]:
x[1,-1] # Extracción del elemento con índice 1 en renglón y primer elemento en forma descendente

9

In [9]:
x[0] # Extracción del renglón completo con índice 0 (al no especificar índice de columna)

array([0, 1, 2, 3, 4])

In [10]:
# Cortes en arreglos
x = np.array([0,1,2,3,4,5,6,7,8,9])
x[1:7:2] # Formato: start:stop:step

array([1, 3, 5])

In [11]:
x[-2:10] # Corte del arreglo de adelante hacia atrás, considerando 2 elementos

array([8, 9])

In [12]:
# Corte del arreglo de adelante hacia atrás, iniciando 3 posiciones a partir del final y retrocediendo en 1
# hasta tener como límite el número 3
x[-3:3:-1]

array([7, 6, 5, 4])

In [13]:
# Definición de un nuevo arreglo
x = np.arange(10, 1, -1) # Creación de un arreglo en forma descendente - Del 10 al 1 (sin incluirlo) con decrementos en 1
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [14]:
# Extracción de elementos específicos del arreglo
x[np.array([3,3,1,8])] # Extracción de elementos con índice 3, 3, 1 y 8

array([7, 7, 9, 2])

In [15]:
x[np.array([3,3,-3,8])] # Extracción de elementos con índices 3, 3, -3 (descendente) y 8

array([7, 7, 4, 2])

In [16]:
# Extracción basada en pares
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [17]:
y[np.array([0,2,4]), np.array([0,1,2])] # Extracción de 'coordenadas' (0,0), (2,1) y (4,2)

array([ 0, 15, 30])

# Unión de arreglos

In [18]:
# Concatenación de vectores
arr = np.concatenate(([1,2,3], [4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

In [19]:
# Apilado vertical de vectores
np.stack(([1,2,3], [4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# Concatenación de matrices
mat_1 = np.array([[1,2,3], [4,5,6]])
mat_2 = np.array([[1,1,1], [2,2,2]])
np.concatenate((mat_1, mat_2), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [21]:
np.concatenate((mat_1, mat_2), axis=1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [22]:
np.concatenate((mat_1, mat_2), axis=None)

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])